# Generated by Django 3.2.6 on 2021-08-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='habilidad',
            field=models.ManyToManyField(to='registro.Habilidad'),
        ),
    ]
