# Generated by Django 3.2.6 on 2021-09-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_empleado_habilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='registro', verbose_name='Imagen'),
        ),
    ]
